"""
File Router Module

Handles routing of validated files to appropriate GCS destinations based on
validation results and business rules. This module focuses purely on file
routing logic without performing validation or processing.

Key Responsibilities:
- Route PASS files to processed/ folder with Hive partitioning
- Route FAIL files to failed/ folder for manual review
- Generate destination paths based on entity type and date
- Coordinate with CloudStorageManager for async file operations
- Track routing metrics and success rates

Routing Rules:
- PASS: gs://bucket/processed/{entity_type}/load_type=delta/date=YYYY-MM-DD/filename.csv
- FAIL: gs://bucket/failed/filename
- Source files in inbox/ are moved (not copied) to final destinations

Author: Manish Arora
Version: 1.0
"""

import asyncio
import logging
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass
from .cloud_storage_manager import CloudStorageManager
from .file_validator import ValidationResult
from .cloud_logging import CloudLogging
from . import settings

# Configure logging
logger = logging.getLogger(__name__)

@dataclass(frozen=True)
class RoutingResult:
    """
    Represents the result of file routing operation.
    
    Attributes:
        filename (str): Name of the routed file
        validation_id (str): Validation ID for correlation. Validation_id is generated by the FileValidator class using the method generate_validation_id().
        success (bool): Whether routing was successful
        source_path (str): Original file path in inbox/
        destination_path (Optional[str]): Final destination path
        routing_type (str): Type of routing (passed/failed)
        error_message (Optional[str]): Error details if routing failed
        duration_ms (int): Routing operation duration
    """
    filename: str
    validation_id: str  
    success: bool
    source_path: str
    destination_path: Optional[str]
    routing_type: str
    error_message: Optional[str]
    duration_ms: int

class FileRouter:
    """
    Handles routing of validated files to appropriate GCS destinations.
    
    This class implements business rules for file placement based on validation
    results, with support for Hive partitioning and error isolation.
    """
    
    def __init__(self):
        """
        Initialize the File Router with storage client and configuration.
        """
        self.storage_manager = CloudStorageManager()
        self.project_id = settings.get_project_id()

    def _generate_destination_path(self, validation_result: ValidationResult) -> str:
        """
        Generate destination path for processed files based on load type. The path is prepared to support HIVE partitioning
        
        Args:
            validation_result (ValidationResult): Validation result containing metadata
            
        Returns:
            str: Destination path based on load type
            
        Examples:
            Full files: processed/customers/load_type=full/customers_20260101.csv
            Delta files: processed/customers/load_type=delta/date=2026-01-01/batch_01_customers_delta.csv
        """
        entity_type = validation_result.metadata.get('entity_type', 'unknown') # From file_metadata_extractor
        load_type = validation_result.metadata.get('load_type', 'full') # From file_metadata_extractor
        file_date = validation_result.metadata.get('file_date') # From file_metadata_extractor
        
        if load_type == 'full':
            return f"processed/{entity_type}/load_type=full/{validation_result.filename}"
        elif load_type == 'delta':
            # Convert YYYYMMDD to YYYY-MM-DD format for delta files
            if file_date and len(file_date) == 8:  # Format: YYYYMMDD
                year = file_date[:4]
                month = file_date[4:6]
                day = file_date[6:8]
                formatted_date = f"{year}-{month}-{day}"
            else:
                # Fallback to current date if file_date is invalid
                now = datetime.now(timezone.utc)
                formatted_date = f"{now.year}-{now.month:02d}-{now.day:02d}"
            
            return f"processed/{entity_type}/load_type=delta/date={formatted_date}/{validation_result.filename}"
        else:
            # Fallback for unknown load types
            return f"processed/{entity_type}/load_type=full/{validation_result.filename}"

    def test_generate_destination_path(self) -> None:
        """
        Test method for _generate_destination_path with various scenarios.
        
        This method tests the new load_type partitioning pattern for both
        full and delta files with different date scenarios.
        """
        from .file_validator import ValidationResult
        
        print("🧪 Testing _generate_destination_path method")
        print("=" * 60)
        
        # Test Case 1: Full load customer file
        print("\n📋 Test Case 1: Full Load Customer File")
        full_metadata = {
            'entity_type': 'customers',
            'load_type': 'full',
            'file_date': '20260101',
            'batch_id': None
        }
        full_result = ValidationResult(
            filename="customers_20260101.csv",
            validation_id="test_001",
            passed=True,
            failed_checks=[],
            error_details={},
            metadata=full_metadata,
            file_size_bytes=1024
        )
        
        full_path = self._generate_destination_path(full_result)
        expected_full = "processed/customers/load_type=full/customers_20260101.csv"
        print(f"Input: {full_result.filename}")
        print(f"Expected: {expected_full}")
        print(f"Actual:   {full_path}")
        print(f"✅ Match: {full_path == expected_full}")
        
        # Test Case 2: Delta load customer file with valid date
        print("\n📋 Test Case 2: Delta Load Customer File (Valid Date)")
        delta_metadata = {
            'entity_type': 'customers',
            'load_type': 'delta',
            'file_date': '20260414',
            'batch_id': 'batch_001'
        }
        delta_result = ValidationResult(
            filename="batch_01_customers_delta.csv",
            validation_id="test_002",
            passed=True,
            failed_checks=[],
            error_details={},
            metadata=delta_metadata,
            file_size_bytes=2048
        )
        
        delta_path = self._generate_destination_path(delta_result)
        expected_delta = "processed/customers/load_type=delta/date=2026-04-14/batch_01_customers_delta.csv"
        print(f"Input: {delta_result.filename}")
        print(f"Expected: {expected_delta}")
        print(f"Actual:   {delta_path}")
        print(f"✅ Match: {delta_path == expected_delta}")
        
        # Test Case 3: Delta load with invalid date (fallback to current date)
        print("\n📋 Test Case 3: Delta Load with Invalid Date (Current Date Fallback)")
        delta_invalid_metadata = {
            'entity_type': 'orders',
            'load_type': 'delta',
            'file_date': None,  # Invalid date
            'batch_id': 'batch_002'
        }
        delta_invalid_result = ValidationResult(
            filename="batch_02_orders_delta.csv",
            validation_id="test_003",
            passed=True,
            failed_checks=[],
            error_details={},
            metadata=delta_invalid_metadata,
            file_size_bytes=4096
        )
        
        delta_invalid_path = self._generate_destination_path(delta_invalid_result)
        # Current date will vary, so we just check the pattern
        print(f"Input: {delta_invalid_result.filename}")
        print(f"Output: {delta_invalid_path}")
        print(f"✅ Contains load_type=delta: {'load_type=delta' in delta_invalid_path}")
        print(f"✅ Contains date= pattern: {'date=' in delta_invalid_path}")
        
        # Test Case 4: Unknown load type (fallback to full)
        print("\n📋 Test Case 4: Unknown Load Type (Fallback to Full)")
        unknown_metadata = {
            'entity_type': 'products',
            'load_type': 'unknown_type',
            'file_date': '20260301',
            'batch_id': None
        }
        unknown_result = ValidationResult(
            filename="products_20260301.csv",
            validation_id="test_004",
            passed=True,
            failed_checks=[],
            error_details={},
            metadata=unknown_metadata,
            file_size_bytes=8192
        )
        
        unknown_path = self._generate_destination_path(unknown_result)
        expected_unknown = "processed/products/load_type=full/products_20260301.csv"
        print(f"Input: {unknown_result.filename}")
        print(f"Expected: {expected_unknown}")
        print(f"Actual:   {unknown_path}")
        print(f"✅ Match: {unknown_path == expected_unknown}")
        
        # Test Case 5: Order Items Full Load
        print("\n📋 Test Case 5: Order Items Full Load")
        order_items_metadata = {
            'entity_type': 'order_items',
            'load_type': 'full',
            'file_date': '20260501',
            'batch_id': None
        }
        order_items_result = ValidationResult(
            filename="order_items_20260501.csv",
            validation_id="test_005",
            passed=True,
            failed_checks=[],
            error_details={},
            metadata=order_items_metadata,
            file_size_bytes=16384
        )
        
        order_items_path = self._generate_destination_path(order_items_result)
        expected_order_items = "processed/order_items/load_type=full/order_items_20260501.csv"
        print(f"Input: {order_items_result.filename}")
        print(f"Expected: {expected_order_items}")
        print(f"Actual:   {order_items_path}")
        print(f"✅ Match: {order_items_path == expected_order_items}")
        
        print("\n" + "=" * 60)
        print("🎉 Path generation testing completed!")
        print("📊 All test cases validate the new load_type partitioning pattern")

    async def _route_single_file(
        self,
        bucket_name: str,
        validation_result: ValidationResult
    ) -> RoutingResult:
        """
        Route a single validated file to its destination.
        
        Args:
            bucket_name (str): GCS bucket name
            validation_result (ValidationResult): Validation result for the file
            
        Returns:
            RoutingResult: Result of the routing operation
        """
        start_time = datetime.now()
        source_path = f"inbox/{validation_result.filename}"
        
        try:
            if validation_result.passed:
                # Route to processed/ with Hive partitioning
                destination_path = self._generate_destination_path(validation_result)
                routing_type = "passed"
            else:
                # Route to failed/ for manual review
                destination_path = f"failed/{validation_result.filename}"
                routing_type = "failed"
            
            # Move file to destination
            move_success = await self.storage_manager.move_file_from_inbox_to_destination(
                bucket_name=bucket_name,
                source_filename=validation_result.filename,
                destination_path=destination_path
            )
            
            end_time = datetime.now()
            duration_ms = int((end_time - start_time).total_seconds() * 1000)
            
            if move_success:
                # Log successful routing
                CloudLogging.log_cloud_storage_operation(
                    operation="move",
                    source_path=f"gs://{bucket_name}/{source_path}",
                    destination_path=f"gs://{bucket_name}/{destination_path}",
                    success=True,
                    duration_ms=duration_ms
                )
                
                return RoutingResult(
                    filename=validation_result.filename,
                    validation_id=validation_result.validation_id,
                    success=True,
                    source_path=source_path,
                    destination_path=destination_path,
                    routing_type=routing_type,
                    error_message=None,
                    duration_ms=duration_ms
                )
            else:
                return RoutingResult(
                    filename=validation_result.filename,
                    validation_id=validation_result.validation_id,
                    success=False,
                    source_path=source_path,
                    destination_path=destination_path,
                    routing_type=routing_type,
                    error_message="File move operation failed",
                    duration_ms=duration_ms
                )
                
        except Exception as e:
            end_time = datetime.now()
            duration_ms = int((end_time - start_time).total_seconds() * 1000)
            
            error_message = f"Routing error: {str(e)}"
            
            # Log failed routing
            CloudLogging.log_cloud_storage_operation(
                operation="move",
                source_path=f"gs://{bucket_name}/{source_path}",
                destination_path=f"gs://{bucket_name}/{destination_path if 'destination_path' in locals() else 'unknown'}",
                success=False,
                duration_ms=duration_ms,
                error_message=error_message
            )
            
            return RoutingResult(
                filename=validation_result.filename,
                validation_id=validation_result.validation_id,
                success=False,
                source_path=source_path,
                destination_path=None,
                routing_type="error",
                error_message=error_message,
                duration_ms=duration_ms
            )

    async def route_validated_files(
        self,
        bucket_name: str,
        validation_results: List[ValidationResult]
    ) -> List[RoutingResult]:
        """
        Route multiple validated files to their destinations concurrently.
        
        Args:
            bucket_name (str): GCS bucket name
            validation_results (List[ValidationResult]): Results from file validation
            
        Returns:
            List[RoutingResult]: Results for each routing operation
        """
        routing_tasks = [
            self._route_single_file(bucket_name, result)
            for result in validation_results
        ]
        
        results = await asyncio.gather(*routing_tasks, return_exceptions=True)
        
        # Handle any exceptions in the results
        final_results = []
        for i, result in enumerate(results):
            if isinstance(result, Exception):
                validation_result = validation_results[i]
                final_results.append(RoutingResult(
                    filename=validation_result.filename,
                    validation_id=validation_result.validation_id,
                    success=False,
                    source_path=f"inbox/{validation_result.filename}",
                    destination_path=None,
                    routing_type="error",
                    error_message=f"Routing exception: {str(result)}",
                    duration_ms=0
                ))
            else:
                final_results.append(result)
        
        # Log batch routing metrics
        await self._log_batch_routing_metrics(bucket_name, final_results)
        
        return final_results
    

    
    
    async def _log_batch_routing_metrics(
        self,
        bucket_name: str,
        routing_results: List[RoutingResult]
    ) -> None:
        """
        Log batch routing metrics for operational monitoring.
        
        Args:
            bucket_name (str): GCS bucket name
            routing_results (List[RoutingResult]): Results from routing operations
        """
        total_files = len(routing_results)
        successful_routes = sum(1 for r in routing_results if r.success)
        failed_routes = total_files - successful_routes
        
        passed_files = sum(1 for r in routing_results if r.routing_type == "passed" and r.success)
        failed_files = sum(1 for r in routing_results if r.routing_type == "failed" and r.success)
        error_files = sum(1 for r in routing_results if r.routing_type == "error")
        
        avg_duration_ms = sum(r.duration_ms for r in routing_results) / total_files if total_files > 0 else 0
        
        # Log routing summary
        logger.info(
            f"Batch routing completed: {successful_routes}/{total_files} files routed successfully",
            extra={
                'bucket_name': bucket_name,
                'total_files': total_files,
                'successful_routes': successful_routes,
                'failed_routes': failed_routes,
                'passed_files': passed_files,
                'failed_files': failed_files,
                'error_files': error_files,
                'avg_duration_ms': avg_duration_ms,
                'event_type': 'batch_routing_complete',
                'timestamp': datetime.now(timezone.utc).isoformat()
            }
        )
    
    async def route_single_validated_file(
        self,
        bucket_name: str,
        validation_result: ValidationResult
    ) -> RoutingResult:
        """
        Route a single validated file (convenience method for single file operations).
        
        Args:
            bucket_name (str): GCS bucket name
            validation_result (ValidationResult): Validation result for the file
            
        Returns:
            RoutingResult: Result of the routing operation
        """
        return await self._route_single_file(bucket_name, validation_result)
    
    def get_expected_destination_path(self, validation_result: ValidationResult) -> str:
        """
        Get the expected destination path without performing the routing operation.
        
        Args:
            validation_result (ValidationResult): Validation result for the file
            
        Returns:
            str: Expected destination path
        """
        if validation_result.passed:
            return self._generate_destination_path(validation_result)
        else:
            return f"failed/{validation_result.filename}"