# ==============================================================================
# Module: Cloud Monitoring and Alerting
# Description: Log-based metrics and alert policies for pipeline monitoring
# ==============================================================================

# Log-based metric: Cloud Run validator errors when validating source files in the raw zone
#  This constuct is simply a metric that is created on the basis of the logs generated by the Cloud Run validator
#  The filter applies on the logs generated by the Cloud Run validator which is executed under Service Account: Cloud Run Validator, and severity is ERROR
resource "google_logging_metric" "validator_errors" {
  name   = "${var.name_prefix}_validator_errors"
  # The cloud_run_revision is a label that is automatically added to the logs by Cloud Run
  filter = "resource.type=\"cloud_run_revision\" AND resource.labels.service_name=\"${var.name_prefix}-validator\" AND severity=\"ERROR\""
  
  metric_descriptor {
    metric_kind = "GAUGE"
    value_type  = "INT64"
    display_name = "Validator Error Count"
  }
  
  # The value_extractor extracts the error_count from the jsonPayload of the log entry
  value_extractor = "EXTRACT(jsonPayload.error_count)"
  
  # label extractor extracts the entity_type and error_type from the jsonPayload of the log entry. This is used for grouping the logs
  label_extractors = {
    "entity_type" = "EXTRACT(jsonPayload.entity_type)"
    "error_type"  = "EXTRACT(jsonPayload.error_type)"
  }
}

# Log-based metric: Pipeline failures
# The filter applies on the logs generated by the Cloud Run orchestrator which is executed under Service Account: Cloud Run Orchestrator, and severity is ERROR
resource "google_logging_metric" "pipeline_failures" {
  name   = "${var.name_prefix}_pipeline_failures"

  filter = "resource.type=\"cloud_run_revision\" AND resource.labels.service_name=\"${var.name_prefix}-orchestrator\" AND severity=\"ERROR\""
  
  metric_descriptor {
    metric_kind = "GAUGE"
    #  metric_kind of GAUGE means the value is measured at a specific point in time
    value_type  = "INT64"
    # value_type of INT64 means the value is an integer
    display_name = "Pipeline Failure Count"
  }
  
  # The value_extractor extracts the failure_count from the jsonPayload of the log entry
  value_extractor = "EXTRACT(jsonPayload.failure_count)"
  
  # label extractor extracts the pipeline_name and failure_reason from the jsonPayload of the log entry. This is used for grouping the logs
  label_extractors = {
    "pipeline_name" = "EXTRACT(jsonPayload.pipeline_name)"
    "failure_reason" = "EXTRACT(jsonPayload.failure_reason)"
  }
}

# Notification channel: Pub/Sub
# google_monitoring_notification_channel is used for creating notification channels. Notification channels are used to send alerts to different channels
# this is similar to sending someone a notification when something goes wrong. There can be different channels for communication like email, slack, pub/sub, etc.
resource "google_monitoring_notification_channel" "pubsub_alerts" {
  # display_name is the name of the notification channel
  display_name = "${var.name_prefix} Pub/Sub Alerts"
  # type is the type of the notification channel
  type         = "pubsub"
  
  # labels are used to store the topic name
  labels = {
    topic = var.escalation_alerts_topic
  }
}

# Notification channel: Email (if provided)
resource "google_monitoring_notification_channel" "email_alerts" {
  # count is used to create a notification channel only if the notification email is provided
  count = var.notification_email != "" ? 1 : 0
  
  display_name = "${var.name_prefix} Email Alerts"
  type         = "email"
  
  # labels are used to store the email address
  labels = {
    email_address = var.notification_email
  }
}

# Alert policy: Validator errors
# google_monitoring_alert_policy is used for creating alert policies. Alert policies are used to send alerts to different channels
# the google_monitoring_alert_policy is a resource that is used to create alert policies when a certain threshold is reached. 
# As an example in AWS, when an EC2 instance CPU utilization crosses 80% for 5 minutes, an alert is triggered. 
# Similarly, here we are creating an alert policy for the validator errors using condition_threshold. 
resource "google_monitoring_alert_policy" "validator_error_alert" {
  display_name = "${var.name_prefix} Validator Errors"
  combiner     = "OR"
  
  # conditions are used to specify the conditions for the alert policy
  conditions {
    display_name = "Validator error rate"

    #  The below threshold is set to 0, which means that if the validator errors are greater than 0, an alert will be triggered
    #  The duration of 300s means that the alert will be triggered if the validator errors are greater than 0 for 5 minutes
    #  The comparison is set to COMPARISON_GT, which means that the alert will be triggered if the validator errors are greater than 0
    #  The threshold_value is set to 0, which means that the alert will be triggered if the validator errors are greater than 0
    #  The aggregations block is used to aggregate the logs.
    #  This configuration is similar to creating an alert policy on GCP console
    
    condition_threshold {
      # filter is used to filter the logs
      filter         = "metric.type=\"logging.googleapis.com/user/${var.name_prefix}_validator_errors\" AND resource.type=\"global\""
      duration       = "300s"
      comparison     = "COMPARISON_GT"
      threshold_value = 0
      
      aggregations {
        alignment_period   = "300s"
        per_series_aligner = "ALIGN_SUM"
      }
    }
  }
  
  #  The notification_channels is a list of notification channels that will be notified when an alert is triggered
  #  The concat function is used to concatenate the notification channels.
  #  The pubsub_alerts is a list of notification channels that will be notified when an alert is triggered
  #  The email_alerts is a list of notification channels that will be notified when an alert is triggered
  #  The concat function is used to concatenate the notification channels.
  notification_channels = concat(
    [google_monitoring_notification_channel.pubsub_alerts.id],
    var.notification_email != "" ? [google_monitoring_notification_channel.email_alerts[0].id] : []
  )
  
  alert_strategy {
    auto_close = "1800s"
  }
}

# Alert policy: Pipeline failures
resource "google_monitoring_alert_policy" "pipeline_failure_alert" {
  display_name = "${var.name_prefix} Pipeline Failures"
  combiner     = "OR"
  
  conditions {
    display_name = "Pipeline failure rate"
    
    condition_threshold {
      filter         = "metric.type=\"logging.googleapis.com/user/${var.name_prefix}_pipeline_failures\" AND resource.type=\"global\""
      duration       = "300s"
      comparison     = "COMPARISON_GT"
      threshold_value = 0
      
      aggregations {
        alignment_period   = "300s"
        per_series_aligner = "ALIGN_SUM"
      }
    }
  }
  
  notification_channels = concat(
    [google_monitoring_notification_channel.pubsub_alerts.id],
    var.notification_email != "" ? [google_monitoring_notification_channel.email_alerts[0].id] : []
  )
  
  alert_strategy {
    auto_close = "1800s"
  }
}

# Dashboard: Pipeline Health
# Create a new Dashboard on Cloud Monitoring
resource "google_monitoring_dashboard" "pipeline_health" {
  dashboard_json = jsonencode({
    displayName = "${var.name_prefix} Pipeline Health"
    
    mosaicLayout = {
      tiles = [
        {
          width = 6
          height = 4
          widget = {
            title = "Validator Errors"
            scorecard = {
              timeSeriesQuery = {
                timeSeriesFilter = {
                  filter = "metric.type=\"logging.googleapis.com/user/${var.name_prefix}_validator_errors\""
                  aggregation = {
                    alignmentPeriod = "300s"
                    perSeriesAligner = "ALIGN_SUM"
                  }
                }
              }
              sparkChartView = {
                sparkChartType = "SPARK_BAR"
              }
            }
          }
        },
        {
          width = 6
          height = 4
          widget = {
            title = "Pipeline Failures"
            scorecard = {
              timeSeriesQuery = {
                timeSeriesFilter = {
                  filter = "metric.type=\"logging.googleapis.com/user/${var.name_prefix}_pipeline_failures\""
                  aggregation = {
                    alignmentPeriod = "300s"
                    perSeriesAligner = "ALIGN_SUM"
                  }
                }
              }
              sparkChartView = {
                sparkChartType = "SPARK_BAR"
              }
            }
          }
        }
      ]
    }
  })
}